(function(g){var window=this;var Mwa=function(a,b,c,d){var e=b.gc();g.S(a.element,"ytp-suggestion-set",!!e.videoId);var f=b.getPlaylistId();d=b.dc(c,d?d:"mqdefault.jpg");var k=b instanceof g.GP?g.oW(b.lengthSeconds):null,l=!!f,f=l&&"RD"==g.lR(f).type,m=b instanceof g.GP?b.Aa:null;c={title:b.title,author:b.author,author_and_views:e.shortViewCount?b.author+" \u2022 "+e.shortViewCount:b.author,watch:g.T("YTP_WATCH_VIDEO_OR_PLAYLIST",{TITLE:b.title},b.title),duration:k,url:b.nn(c),is_live:m,is_list:l,is_mix:f,background:d?"background-image: url("+
d+")":""};b instanceof g.nR&&(c.playlist_length=b.getLength());a.update(c)},T7=function(a,b){g.iW.call(this,{H:"div",
ca:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.o=a;this.O=!1},U7=function(a){var b={H:"span",
N:"ytp-upnext-top",L:[{H:"span",N:"ytp-upnext-header",L:[g.T("YTP_PLAYLIST_UP_NEXT")]},{H:"span",N:"ytp-upnext-title",L:["{{title}}"]},{H:"span",N:"ytp-upnext-author",L:["{{author}}"]}]},c={href:"{{url}}","aria-label":g.T("YTP_AUTOPLAY_NEXT")},b={H:"div",N:"ytp-upnext",R:{"aria-label":"{{watch}}"},L:[{H:"div",N:"ytp-cued-thumbnail-overlay-image",R:{style:"{{background}}"}},b,{H:"a",N:"ytp-upnext-autoplay-icon",R:c,L:[{H:"svg",R:{height:"100%",version:"1.1",viewBox:"0 0 98 98",width:"100%"},L:[{H:"circle",
N:"ytp-svg-autoplay-circle",R:{cx:"49",cy:"49",fill:"#000","fill-opacity":"0.8",r:"48"}},{H:"circle",N:"ytp-svg-autoplay-ring",R:{cx:"-49",cy:"49","fill-opacity":"0",r:"46.5",stroke:"#FFFFFF","stroke-dasharray":"293","stroke-dashoffset":"-293","stroke-width":"4",transform:"rotate(-90)"}},{H:"polygon",N:"ytp-svg-autoplay-triangle",R:{fill:"#fff",points:"32,27 72,49 32,71"}}]}]},{H:"span",N:"ytp-upnext-bottom",L:[{H:"span",N:"ytp-upnext-cancel"},{H:"span",N:"ytp-upnext-paused",L:[g.T("YTP_AUTOPLAY_PAUSED_3")]}]},
{H:"span",N:"ytp-upnext-close"}]};g.X.call(this,b);this.B=null;c=this.wa["ytp-upnext-cancel"];b=this.wa["ytp-upnext-close"];this.B=new g.X({H:"button",ca:["ytp-upnext-cancel-button","ytp-button"],R:{tabindex:0,"aria-label":g.T("YTP_AUTOPLAY_CANCEL")},L:[g.T("YTP_CANCEL")]});g.L(this,this.B);this.B.V("click",this.qA,this);this.B.Fa(c);c=new g.X({H:"button",ca:["ytp-upnext-close-button","ytp-button"],R:{"aria-label":g.T("YTP_AUTOPLAY_CANCEL")}});g.L(this,c);c.V("click",this.qA,this);c.Fa(b);this.o=
a;this.K=this.wa["ytp-svg-autoplay-ring"];this.F=this.D=this.A=this.C=null;this.G=new g.Gt(this.Hm,5E3,this);g.L(this,this.G);this.J=0;this.T(this.wa["ytp-upnext-autoplay-icon"],"click",this.YP);this.nA();this.T(a,"autonavvisibility",this.nA);this.T(a,"mdxnowautoplaying",this.oP);this.T(a,"mdxautoplaycanceled",this.pP);this.T(a,"mdxautoplayupnext",this.vC);3==this.o.Xa()&&(a=(a=g.fV(g.aV(this.o)))?a.AH():null)&&this.vC(a)},Nwa=function(a,b){a.C=b;
Mwa(a,b,g.W(a.o),"hqdefault.jpg")},V7=function(a,b){a.A||(g.uG("a11y-announce",g.T("YTP_PLAYLIST_UP_NEXT")+" "+a.C.title),a.J=(0,g.HG)(),a.A=new g.Gt((0,g.y)(a.Mp,a,b),25),a.Mp(b));
g.Vp(a.element,"ytp-upnext-autoplay-paused")},X7=function(a){W7(a);
a.J=(0,g.HG)();a.Mp();g.R(a.element,"ytp-upnext-autoplay-paused")},W7=function(a){a.A&&(a.A.dispose(),a.A=null)},Owa=function(a){T7.call(this,a,"subscribecard-endscreen");
var b=a.ha();this.A=new g.X({H:"div",N:"ytp-subscribe-card",L:[{H:"img",N:"ytp-author-image",R:{src:b.profilePicture}},{H:"div",N:"ytp-subscribe-card-right",L:[{H:"div",N:"ytp-author-name",L:[b.author]},{H:"div",N:"html5-subscribe-button-container"}]}]});g.L(this,this.A);this.A.Fa(this.element);this.B=new g.F1(g.T("YTP_SUBSCRIBE"),null,g.T("YTP_UNSUBSCRIBE"),null,!0,!1,b.El,b.subscribed,"trailer-endscreen",null,null,a);g.L(this,this.B);this.B.Fa(this.A.wa["html5-subscribe-button-container"]);this.hide()},
Y7=function(a){var b=g.W(a),b=b.B&&!b.F;
g.X.call(this,{H:"a",N:"ytp-videowall-still",R:{href:"{{url}}",target:b?"_blank":"","aria-label":"{{watch}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},L:[{H:"div",N:"ytp-videowall-still-image",R:{style:"{{background}}"}},{H:"span",N:"ytp-videowall-still-info",L:[{H:"span",N:"ytp-videowall-still-info-bg",L:[{H:"span",N:"ytp-videowall-still-info-content",R:g.iF||g.Se?{style:"will-change: opacity"}:void 0,L:[{H:"span",N:"ytp-videowall-still-info-title",L:["{{title}}"]},
{H:"span",N:"ytp-videowall-still-info-author",L:["{{author_and_views}}"]},{H:"span",N:"ytp-videowall-still-info-live",L:[g.T("YTP_LIVE")]},{H:"span",N:"ytp-videowall-still-info-duration",L:["{{duration}}"]}]}]}]},{H:"span",ca:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],L:[{H:"span",N:"ytp-videowall-still-listlabel-icon"},g.T("YTP_PLAYLIST"),{H:"span",N:"ytp-videowall-still-listlabel-length",L:[" (",{H:"span",L:["{{playlist_length}}"]},")"]}]},{H:"span",ca:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],L:[{H:"span",N:"ytp-videowall-still-listlabel-mix-icon"},g.T("YTP_MIX"),{H:"span",N:"ytp-videowall-still-listlabel-length",L:[" (50+)"]}]}]});this.B=b;this.o=a;this.A=null;this.V("click",this.C);this.V("keypress",this.D);if(g.W(a).ea){a=a.app.ea;b=this.element;g.eb(a.g,b);g.ib(a.g,b);var c=String(a.G++);b.setAttribute("data-visual-id",c);g.Ne(this,(0,g.y)(a.F,a,b))}},Z7=function(a){T7.call(this,a,"videowall-endscreen");
this.da=a;this.G=0;this.B=[];this.J=this.D=this.C=null;this.K=this.W=!1;this.F=new g.cG(this);g.L(this,this.F);this.M=new g.Gt(g.za(g.R,this.element,"ytp-show-tiles"),0);g.L(this,this.M);var b=new g.X({H:"button",ca:["ytp-button","ytp-endscreen-previous"],R:{"aria-label":g.T("YTP_PREVIOUS")},L:[g.iE()]});g.L(this,b);b.Fa(this.element);b.V("click",this.QL,this);this.P=new g.JV({H:"div",N:"ytp-endscreen-content"});g.L(this,this.P);this.P.Fa(this.element);b=new g.X({H:"button",ca:["ytp-button","ytp-endscreen-next"],
R:{"aria-label":g.T("YTP_NEXT")},L:[g.jE()]});g.L(this,b);b.Fa(this.element);b.V("click",this.PL,this);this.A=new U7(a);g.L(this,this.A);g.CV(this.o,this.A.element,4);this.hide()},$7=function(a){return g.DV(a.o)&&a.Qp()&&!a.J},Pwa=function(a){return(0,g.H)(a.fg,function(a){return g.e_(a)})},Qwa=function(a,b,c){return 0==b&&a.C.length&&2<=c/2&&2<=c/2&&g.W(a.o).experiments.g("video_wall_emphasize_first")?4:2},a8=function(a){var b=a.ls();
b!=a.W&&(a.W=b,a.o.Y("autonavvisibility"))},b8=function(a){g.$V.call(this,a);
g.eE({});this.o=null;this.isAvailable=!0;this.A=new g.cG(this);g.L(this,this.A);this.B=g.W(a);Rwa(a)?this.o=new Z7(this.g):this.B.ra?this.o=new Owa(this.g):this.o=new T7(this.g);g.L(this,this.o);g.CV(this.g,this.o.element,4);this.yB();this.A.T(a,"videodatachange",this.yB,this);this.A.T(a,"crn_endscreen",this.rL,this);this.A.T(a,"crx_endscreen",this.sL,this)},Rwa=function(a){a=g.W(a);
return a.Jc&&!a.ra};g.p(T7,g.iW);T7.prototype.create=function(){this.O=!0};
T7.prototype.destroy=function(){this.O=!1};
T7.prototype.Qp=function(){return!1};
T7.prototype.ls=function(){return!1};g.p(U7,g.X);g.h=U7.prototype;g.h.Hm=function(){this.D&&(this.G.stop(),this.Da(this.F),this.F=null,this.D.close(),this.D=null)};
g.h.nA=function(){g.hW(this,g.bV(this.o))};
g.h.PP=function(){window.focus();this.Hm()};
g.h.hide=function(){g.X.prototype.hide.call(this)};
g.h.Mp=function(a){a=a||g.W(this.o).experiments.o("autoplay_time")||1E4;var b=Math.min((0,g.HG)()-this.J,a);a=Math.min(b/a,1);this.K.setAttribute("stroke-dashoffset",-293*(a+1));1<=a&&3!=this.o.Xa()?this.select(!0):this.A&&this.A.start()};
g.h.select=function(a){a=void 0===a?!1:a;var b=g.W(this.o);if(b.experiments.g("autonav_notifications")&&a&&window.Notification&&window.document.hasFocus){var c=window.Notification.permission;g.pV(this.o,"xwebnotifications",{permission:c});"default"==c?window.Notification.requestPermission():"granted"!=c||window.document.hasFocus()||(c=this.C.gc(),this.Hm(),this.D=new window.Notification(g.T("YTP_PLAYLIST_UP_NEXT"),{body:c.title,icon:c.dc(b)}),this.F=this.T(this.D,"click",this.PP),this.G.start())}W7(this);
this.o.uj(!1,a)};
g.h.YP=function(a){!g.ze(this.B.element,g.TF(a))&&g.PZ(a,this.o)&&this.select()};
g.h.qA=function(){g.qV(this.o,"autonavcancel");g.dV(this.o,!0)};
g.h.oP=function(a){this.o.Xa();this.show();V7(this,a)};
g.h.vC=function(a){this.o.Xa();this.C&&this.C.gc().videoId==a.gc().videoId||Nwa(this,a)};
g.h.pP=function(){this.o.Xa();W7(this);this.hide()};
g.h.X=function(){W7(this);this.Hm();g.X.prototype.X.call(this)};g.p(Owa,T7);g.p(Y7,g.X);Y7.prototype.Ij=function(){var a=this.A.gc().videoId,b=this.A.getPlaylistId();g.q2(this.o.app,a,this.A.Vd,b,void 0,void 0)};
Y7.prototype.C=function(a){g.GV(this.o,this.element);g.PZ(a,this.o,this.B,this.A.Vd||void 0)&&this.Ij()};
Y7.prototype.D=function(a){switch(a.keyCode){case 13:case 32:g.YF(a)||(this.Ij(),g.$F(a))}};g.p(Z7,T7);g.h=Z7.prototype;g.h.create=function(){T7.prototype.create.call(this);var a=this.o.ha();a&&(this.C=Pwa(a),this.D=a);this.sh();this.F.T(this.o,"appresize",this.sh);this.F.T(this.o,"videodatachange",this.RL);this.F.T(this.o,"autonavchange",this.lz);this.F.T(this.o,"autonavcancel",this.OL);this.F.T(this.element,"transitionend",this.dR)};
g.h.destroy=function(){g.eG(this.F);g.Pe(this.B);this.B=[];this.C=null;T7.prototype.destroy.call(this);g.Vp(this.element,"ytp-show-tiles");this.M.stop()};
g.h.Qp=function(){return 1!=this.D.autonavState};
g.h.show=function(){T7.prototype.show.call(this);g.Vp(this.element,"ytp-show-tiles");g.W(this.o).isMobile?g.Ht(this.M):this.M.start();(this.K||this.J&&this.J!=this.D.clientPlaybackNonce)&&g.dV(this.o,!1);var a=$7(this);g.DV(this.o)&&g.W(this.o).experiments.g("ui_logging")&&g.pV(this.o,"end",{cancelButtonShow:a?"1":"0",state:this.Qp()?"enabled":"disabled"});a?(a8(this),2==this.D.autonavState?g.W(this.o).experiments.g("fast_autonav_in_background")&&3==this.o.Qn()?this.A.select(!0):V7(this.A):3==this.D.autonavState&&
X7(this.A)):(g.dV(this.o,!0),a8(this))};
g.h.hide=function(){T7.prototype.hide.call(this);X7(this.A);a8(this)};
g.h.dR=function(a){g.TF(a)==this.element&&this.sh()};
g.h.sh=function(){if(this.C&&this.C.length){g.R(this.element,"ytp-endscreen-paginate");for(var a=g.wh(this.element),b=a.width/a.height,c=96/54,d=2,e=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.C.length,m=Math.pow(2,2),n=l*m,q=Qwa(this,0,k),r=Qwa(this,1,k),n=n+(Math.pow(q,2)-m),n=n+(Math.pow(r,2)-m),n=n-m;0<n&&(d<f||e<k);){var w=d/2,A=e/2,C=d<=f-2&&n>=A*m,B=e<=k-2&&n>=w*m;if((w+1)/A*c/b>b/(w/(A+1)*c)&&B)n-=w*m,e+=2;else if(C)n-=A*m,d+=2;else if(B)n-=w*m,e+=2;else break}c=!1;f=2+q;n>=
3*m&&6>=l*m-n&&(e>=f||d>=f)&&2>=r&&(c=!0);m=96*d;n=54*e;b=m/n<b?a.height/n:a.width/m;b=Math.min(b,2);m*=b;n*=b;m*=g.Kd(a.width/m||1,1,1.21);n*=g.Kd(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.P.element;g.vh(a,m,n);g.dh(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});Nwa(this.A,this.C[0]);g.S(this.element,"ytp-endscreen-takeover",$7(this));a8(this);m+=4;n+=4;b=0;f=!1;for(k=0;k<d;k++)for(w=0;w<e;w++)if(A=2<r&&1<=b&&!f?b+1:b,C=0,c&&k>=d-2&&w>=e-2?C=
1:0==w%2&&0==k%2&&(w<q&&k<q?0==w&&0==k&&(C=q):2<r&&w>=e-r&&k>=d-r?w==e-r&&k==d-r&&(f=!0,A=1,C=r):C=2),A=g.Ld(A+this.G,l),0!=C){B=this.B[b];B||(B=new Y7(this.o),this.B[b]=B,a.appendChild(B.element));var N=Math.floor(n*w/e),Y=Math.floor(m*k/d),Va=Math.floor(n*(w+C)/e)-N-4,nb=Math.floor(m*(k+C)/d)-Y-4;g.kh(B.element,Y,N);g.vh(B.element,nb,Va);g.dh(B.element,"transitionDelay",(w+k)/20+"s");g.S(B.element,"ytp-videowall-still-mini",1==C);g.S(B.element,"ytp-videowall-still-large",2<C);C=B;A=this.C[A];C.A=
A;Mwa(C,A,g.W(C.o),g.Tp(C.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg");B=A.Vd;A=C.o;g.W(A).ea&&(A=A.app.ea,C=C.element,B=B&&B.itct,N=C.getAttribute("data-visual-id"),g.eb(A.g,C),g.EV(A,"onLogServerVeCreated",{id:N,tracking_params:B}));b++}g.S(this.element,"ytp-endscreen-paginate",b<l);for(d=this.B.length-1;d>=b;d--)e=this.B[d],g.se(e.element),g.Oe(e);this.B.length=b}};
g.h.RL=function(){var a=this.o.ha();this.D!=a&&(this.G=0,this.C=Pwa(a),this.D=a,this.sh())};
g.h.PL=function(){this.G+=this.B.length;this.sh()};
g.h.QL=function(){this.G-=this.B.length;this.sh()};
g.h.JJ=function(){return!!this.A.A};
g.h.lz=function(a){1==a?(this.K=!1,this.J=this.D.clientPlaybackNonce,W7(this.A),this.g&&this.sh()):(this.K=!0,this.g&&$7(this)&&(2==a?V7(this.A):3==a&&X7(this.A)))};
g.h.OL=function(a){if(a){for(a=0;a<this.B.length;a++)g.HV(this.da,this.B[a].element,!0);this.lz(1)}else this.J=null,this.K=!1;this.sh()};
g.h.ls=function(){return this.g&&$7(this)};g.p(b8,g.$V);g.h=b8.prototype;g.h.iz=function(){var a=this.g.ha(),b=!Rwa(this.g)||!(!a.fg||!a.fg.length),a=g.aQ(a,"ypc_module"),c=g.r2(this.g.app);return(b||!1)&&!a&&!c};
g.h.hz=function(){return this.o.ls()};
g.h.GJ=function(){return this.hz()?this.o.JJ():!1};
g.h.X=function(){g.yV(this.g,"endscreen");g.$V.prototype.X.call(this)};
g.h.load=function(){g.$V.prototype.load.call(this);this.o.show();g.W(this.g).ra&&.01>Math.random()&&g.pV(this.g,"end",{trailerEndscreenShow:1})};
g.h.unload=function(){g.$V.prototype.unload.call(this);this.o.hide();this.o.destroy();this.isAvailable=!1};
g.h.rL=function(a){this.iz()&&(this.o.O||this.o.create(),"load"==a.getId()&&this.load())};
g.h.sL=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.yB=function(){g.yV(this.g,"endscreen");var a=Math.max(1E3*(this.g.ha().lengthSeconds-10),0),a=new g.EJ(a,0x8000000000000,{id:"preload",namespace:"endscreen"}),b=new g.EJ(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.vV(this.g,[a,b])};g.rW("endscreen",b8);})(_yt_player);
